default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ashu@855496
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: blog_post_comment_development


test:
  <<: *default
  database: blog_post_comment_test


production:
  <<: *default
  database: blog_post_commen_production
  username: blog_post_commen
  password: <%= ENV['PROJECTNAME_DATABASE_PASSWORD'] %>


 